name: CMake

on:
  push:
    branches:
      - "master"
      - "ci"
  pull_request:
    branches:
      - "master"
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        build_type: ["Release", "Debug"]
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "true"

      - uses: actions/checkout@v3
        with:
          repository: "microsoft/vcpkg"
          path: vcpkg

      - name: Bootstrap vcpkg
        run: ${{github.workspace}}/vcpkg/bootstrap-vcpkg.bat

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build --preset vs2022-windows
        env:
          VCPKG_ROOT: ${{github.workspace}}/vcpkg
          Skyrim64Path: ${{github.workspace}}/

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}}

      - name: Create Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{matrix.build_type}}
          path: ${{github.workspace}}/build/src/${{matrix.build_type}}/
